/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.FileController;
import controllers.Utils;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.product;
import static views.ManagementAccountView.tableModal;
import static views.ManagementAccountView.utils;

/**
 *
 * @author Minh Phuong Do
 */
public class ManagementProductView extends javax.swing.JPanel {

    /**
     * Creates new form ManagementProductView
     */
    private javax.swing.table.DefaultTableModel model;
    static DefaultTableModel tableModal;
    static List<product> listProduct = new ArrayList<product>();
    static FileController file;

    public void increaseIndex() {
        Integer lastIndex = listProduct.get(listProduct.size() - 1).getmaSP();
        Preferences prefs = Preferences.userRoot().node(this.getClass().getName());
        AtomicInteger autoinc = new AtomicInteger(prefs.getInt("autoincrement", lastIndex));
        idspField.setText("" + autoinc.incrementAndGet());
        idspField.setEnabled(false);
        prefs.putInt("autoincrement", autoinc.get());
    }

    public ManagementProductView() {
        initComponents();
        tableModal = (DefaultTableModel) productTable.getModel();
        listProduct = file.readProductFromFile("product.txt");
        for (product item : listProduct) {
            tableModal.addRow(new Object[]{
                item.getmaSP(), item.getTenSP(), item.getGiaBan(), item.getGiaMua(), item.getGiamGia(), item.getSoLuong()
            });
        }
        suajButton.setEnabled(false);
        xoajButton.setEnabled(false);
        //  increaseIndex();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        suajButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        themjButton = new javax.swing.JButton();
        searchFieldProduct = new javax.swing.JTextField();
        tenspField = new java.awt.TextField();
        tensplabel = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        giabanlabel = new java.awt.Label();
        giamuaField = new java.awt.TextField();
        idspField = new java.awt.TextField();
        giamualabel = new java.awt.Label();
        giagiamlabel = new java.awt.Label();
        giagiamField = new java.awt.TextField();
        giabanField = new java.awt.TextField();
        xoajButton = new javax.swing.JButton();
        soluongField = new java.awt.TextField();
        idsplabel = new java.awt.Label();
        soluonglabel = new java.awt.Label();
        jLabel7 = new javax.swing.JLabel();
        showloi = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(985, 670));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        suajButton.setBackground(new java.awt.Color(102, 255, 102));
        suajButton.setText("Sửa");
        suajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suajButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 123, 236));
        jLabel2.setText("QUẢN LÝ SẢN PHẨM");

        themjButton.setBackground(new java.awt.Color(192, 192, 192));
        themjButton.setText("Thêm");
        themjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themjButtonActionPerformed(evt);
            }
        });

        searchFieldProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldProductKeyReleased(evt);
            }
        });

        tenspField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenspFieldActionPerformed(evt);
            }
        });

        tensplabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tensplabel.setText("Tên Sản Phẩm");

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Giá Bán", "GIá Mua", "Giám Giãm", "Số Lượng"
            }
        ));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        giabanlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        giabanlabel.setText("Giá Bán");

        giamuaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giamuaFieldActionPerformed(evt);
            }
        });

        idspField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        idspField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idspFieldActionPerformed(evt);
            }
        });

        giamualabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        giamualabel.setText("Giá Mua");

        giagiamlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        giagiamlabel.setText("Giảm Giá");

        giagiamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giagiamFieldActionPerformed(evt);
            }
        });

        giabanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giabanFieldActionPerformed(evt);
            }
        });

        xoajButton.setBackground(new java.awt.Color(255, 0, 0));
        xoajButton.setForeground(new java.awt.Color(255, 255, 255));
        xoajButton.setText("Xóa");
        xoajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoajButtonActionPerformed(evt);
            }
        });

        soluongField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soluongFieldActionPerformed(evt);
            }
        });

        idsplabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idsplabel.setText("Mã Sản Phẩm");

        soluonglabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        soluonglabel.setText("Số Lượng");

        jLabel7.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tensplabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idsplabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(giabanlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(giamualabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(searchFieldProduct)
                                .addComponent(giamuaField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(idspField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giabanField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenspField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showloi, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(soluonglabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(giagiamlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(giagiamField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(soluongField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(themjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(suajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(xoajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tensplabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(giagiamField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idsplabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idspField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(giagiamlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tenspField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(soluonglabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(soluongField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(giabanField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showloi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(giabanlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(giamualabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(giamuaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchFieldProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(xoajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(suajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(themjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(591, 591, 591))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked

        int row = productTable.getSelectedRow();
        Integer maSP = (Integer) tableModal.getValueAt(row, 0);
        String tenSP = (String) tableModal.getValueAt(row, 1);
        Float giaBan = (Float) tableModal.getValueAt(row, 2);
        Float giaMua = (Float) tableModal.getValueAt(row, 3);
        Float giamGia = (Float) tableModal.getValueAt(row, 4);
        Integer soLuong = (Integer) tableModal.getValueAt(row, 5);

        idspField.setText("" + maSP);
        tenspField.setText(tenSP);
        giabanField.setText("" + giaBan);
        giamuaField.setText("" + giaMua);
        giagiamField.setText("" + giamGia);
        soluongField.setText("" + soLuong);

        idspField.setEnabled(false);
        themjButton.setEnabled(false);
        suajButton.setEnabled(true);
        xoajButton.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_productTableMouseClicked

    private void themjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themjButtonActionPerformed
        //====================================================================
        try {
            Integer maSP = Integer.parseInt(idspField.getText().trim());
            String tenSP = tenspField.getText().trim();
            Float giaBan = Float.parseFloat(giabanField.getText().trim());
            Float giaMua = Float.parseFloat(giamuaField.getText().trim());
            Float giaGiam = Float.parseFloat(giagiamField.getText().trim());
            Integer soLuong = Integer.parseInt(soluongField.getText().trim());

            if (tenSP.compareTo("") == 0) {
                showloi.setText("Vui lòng nhập tên");
                return;
            }
            if (giaBan.equals("")) {
                showloi.setText("Vui lòng nhập giá bán");
                return;
            }

            if (giaMua.equals("")) {
                showloi.setText("Vui lòng nhập giá mua");
                return;
            }

            if (giaGiam.equals("")) {
                showloi.setText("Vui lòng nhập giá giãm");
                return;
            }
            if (soLuong.equals("")) {
                showloi.setText("Vui lòng nhập số luong");
                return;
            }

            showloi.setText(null);

            product product = new product(maSP, tenSP, giaBan, giaMua, giaGiam, soLuong);
            boolean check = false;

            if (check == false) {
                FileController.writeProductToFile("product.txt", product);
                tableModal.addRow(new Object[]{
                    product.getmaSP(), product.getTenSP(), product.getGiaBan(), product.getGiaMua(), product.getGiamGia(), product.getSoLuong()
                });
                listProduct.add(product);
                setTextNull("Thêm sản phẩm mới thành công", "Thêm mới sản phẩm");
                //   increaseIndex();
                tenspField.requestFocus();
            }
        } catch (NumberFormatException e) {
            showloi.setText("Vui lòng lòng nhập đầy đủ thông tin");
        } catch (Exception e) {
            showloi.setText("Vui lòng lòng nhập đầy đủ thông tin");
            showloi.setText(e.toString());
        }

        try {
            Integer maSP = Integer.parseInt(idspField.getText().trim());
            String tenSP = tenspField.getText().trim();
            Float giaBan = Float.parseFloat(giabanField.getText().trim());
            Float giaMua = Float.parseFloat(giamuaField.getText().trim());
            Float giaGiam = Float.parseFloat(giagiamField.getText().trim());
            Integer soLuong = Integer.parseInt(soluongField.getText().trim());

            if (maSP.equals("") || tenSP.equals("") || giaBan.equals("") || giaMua.equals("") || giaGiam.equals("") || soLuong.equals("")) {
                showloi.setText("Vui lòng lòng nhập đầy đủ thông tin");
            }
            showloi.setText("");
            product Product = new product(maSP, tenSP, giaBan, giaMua, giaGiam, soLuong);

            boolean check = false;
            if (check == false) {
                file.writeProductToFile("product.txt", Product);
                tableModal.addRow(new Object[]{
                    Product.getmaSP(), Product.getTenSP(), Product.getGiaBan(), Product.getGiaMua(), Product.getGiamGia(), Product.getSoLuong()
                });
                listProduct.add(Product);
                setTextNull("Thêm sản phẩm mới thành công", "Thêm mới sản phẩm");
                // increaseIndex();
                //JOptionPane.showConfirmDialog(null, "Thêm tài san phâm mới thành công", "Thêm mới", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            showloi.setText("Vui lòng lòng nhập đầy đủ thông tin");
        } catch (Exception e) {
            showloi.setText("Vui lòng lòng nhập đầy đủ thông tin");
            showloi.setText(e.toString());
        }
    }//GEN-LAST:event_themjButtonActionPerformed

    private void suajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suajButtonActionPerformed
        // TODO add your handling code here:
        Integer maSP = Integer.parseInt(idspField.getText().trim());
        String tenSP = tenspField.getText().trim();
        Float giaBan = Float.parseFloat(giabanField.getText().trim());
        Float giaMua = Float.parseFloat(giamuaField.getText().trim());
        Float giamGia = Float.parseFloat(giagiamField.getText().trim());
        Integer soLuong = Integer.parseInt(soluongField.getText().trim());
        int row = productTable.getSelectedRow();

        // update data in file
        product product = new product(maSP, tenSP, giaBan, giaMua, giamGia, soLuong);
        listProduct.set(row, product);
        file.updateListProductToFile("product.txt", listProduct);

        //update UI
        productTable.setValueAt(maSP, row, 0);
        productTable.setValueAt(tenSP, row, 1);
        productTable.setValueAt(giaBan, row, 2);
        productTable.setValueAt(giaMua, row, 3);
        productTable.setValueAt(giamGia, row, 4);
        productTable.setValueAt(soLuong, row, 5);

        suajButton.setEnabled(false);
        xoajButton.setEnabled(false);
        themjButton.setEnabled(true);
        setTextNull("Cập nhật thông tin thành công", "Cập nhật sản phẩm");
        increaseIndex();
    }//GEN-LAST:event_suajButtonActionPerformed

    private void xoajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoajButtonActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa sản phẩm này?", "Xác nhận", JOptionPane.YES_NO_OPTION, 0);
        if (answer == 0) {
            int row = productTable.getSelectedRow();
            tableModal.removeRow(row);

            listProduct.remove(row);
            FileController.updateListProductToFile("product.txt", listProduct);

            suajButton.setEnabled(false);
            xoajButton.setEnabled(false);
            themjButton.setEnabled(true);
            setTextNull("Xóa thành công", "Xóa sản phẩm");
            // increaseIndex();
            tenspField.requestFocus();
        }
    }//GEN-LAST:event_xoajButtonActionPerformed

    private void setTextNull(String title, String subTitle) {
        idspField.setText("");
        tenspField.setText("");
        giabanField.setText("");
        giamuaField.setText("");
        giagiamField.setText("");
        soluongField.setText("");
        JOptionPane.showConfirmDialog(null, title, subTitle, JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }
    private void idspFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idspFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idspFieldActionPerformed

    private void giamuaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giamuaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giamuaFieldActionPerformed

    private void giagiamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giagiamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giagiamFieldActionPerformed

    private void soluongFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soluongFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soluongFieldActionPerformed

    private void tenspFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenspFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenspFieldActionPerformed

    private void giabanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giabanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giabanFieldActionPerformed

    private void searchFieldProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldProductKeyReleased
      // utils.filterByTable(searchFieldProduct, tableModal, productTable);
    }//GEN-LAST:event_searchFieldProductKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField giabanField;
    private java.awt.Label giabanlabel;
    private java.awt.TextField giagiamField;
    private java.awt.Label giagiamlabel;
    private java.awt.TextField giamuaField;
    private java.awt.Label giamualabel;
    private java.awt.TextField idspField;
    private java.awt.Label idsplabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    private javax.swing.JTextField searchFieldProduct;
    private javax.swing.JLabel showloi;
    private java.awt.TextField soluongField;
    private java.awt.Label soluonglabel;
    private javax.swing.JButton suajButton;
    private java.awt.TextField tenspField;
    private java.awt.Label tensplabel;
    private javax.swing.JButton themjButton;
    private javax.swing.JButton xoajButton;
    // End of variables declaration//GEN-END:variables

}
